trigger:
- main  # Or change to your branch name

pool:
  name: Default  # This is the name of your self-hosted agent pool

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Use your installed Node.js version
  displayName: 'Use Node.js'

- script: |
    npm install
    npm run build || echo "No build script found"
  displayName: 'Install dependencies and build'

- script: |
    npm test || echo "No test script found"
  displayName: 'Run tests'

