trigger:
- main

pool:
  name: Default  # Use self-hosted agent, not Microsoft-hosted VM

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Use Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    sudo npm install -g pm2

    cd /home/azureuser/node-app

    pm2 delete node-app || true
    pm2 start index.js --name node-app
    pm2 save
  displayName: '🚀 Deploy Node app using PM2'

