trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    inputs:
      version: '18.x'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build'

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'my-linux-vm'
      sourceFolder: '$(Build.SourcesDirectory)'
      targetFolder: '/home/azureuser/node-app'
      readyTimeout: '20000'

  - script: |
      pm2 restart nodeapp || pm2 start index.js --name nodeapp
    displayName: 'Restart App'

