trigger:
- main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    pm2 stop node-app || true
    pm2 delete node-app || true
    pm2 start index.js --name node-app
    pm2 save
  displayName: 'Restart Node app with PM2'

